POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Peça teatral - O Mágico de OZ",
    "details": "Vemha prestigiar nossos pequenos em uma super peça teatral",
    "maximumAttendees": 100
}