POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Evento teste",
    "details": "Evento teste",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/7a231ce9-be87-4623-976e-0707894469d2/attendees
Content-Type: application/json

{
    "name": "João Silva",
    "email": "joao34@gmail.com"
}


###

GET http://localhost:3333/events/f20c5773-1ca8-4562-b7af-278b73671f86
Content-Type: application/json


###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/4/check-in